### ISSUE TITLE
How would I create my own anim.bin ?

### ISSUE THREAD

**Issue by axonasif** [Mortal/fbspinner#3]
Hi,
fbspinner seems really cool. But I was thinking if I could make a custom `anim.bin` from which image frames are decoded.
I wonder, is `scripts/flatten.py` there for that case ?

**Comment by Mortal** [comment]
Hi @AXIM0S, yes indeed `flatten.py` is the script I used to generate `anim.bin`. You need to create a subdirectory named `anim` and place files named `frame001.png`, `frame002.png`, ... in there, and then run `python3 scripts/flatten.py`. You might need to first run `sudo apt install python3-imageio` or similar to install the `imageio` Python library, which the script uses.

I used `ffmpeg` to convert a video file to png files: `ffmpeg -i INPUT.mp4 anim/frame%03d.png`.

It's been a while since I created this and ran the script to generate `anim.bin`, but I hope you get it working. I'm still running fbspinner on boot on my laptop to this day.

**Comment by axonasif** [comment]
> Hi @AXIM0S, yes indeed `flatten.py` is the script I used to generate `anim.bin`. You need to create a subdirectory named `anim` and place files named `frame001.png`, `frame002.png`, ... in there, and then run `python3 scripts/flatten.py`. You might need to first run `sudo apt install python3-imageio` or similar to install the `imageio` Python library, which the script uses.
> 
> I used `ffmpeg` to convert a video file to png files: `ffmpeg -i INPUT.mp4 anim/frame%03d.png`.
> 
> It's been a while since I created this and ran the script to generate `anim.bin`, but I hope you get it working. I'm still running fbspinner on boot on my laptop to this day.

Thankfully I had most of the stuff figured out already but then as i was trying to execute the script while being on `scripts` dir, so i got an error which says `AssertionError` in the end.

But I never thought of executing the script in the `python3 scripts/flatten.py` way as you've mentioned :sweat_smile:, which solves the `AssertionError` issue but now I get another error :sweat_smile: which says:

![image](https://user-images.githubusercontent.com/39482679/102122962-767b8d80-3e70-11eb-95de-a83b251c3ab0.png)


I'm using frames of a butterfly just for testing it:

![image](https://user-images.githubusercontent.com/39482679/102123695-6d3ef080-3e71-11eb-9b94-947453b5f8ee.png)

Thanks.

Edit: My python version is `3.8.5` btw.

**Comment by Mortal** [comment]
Please don't screenshot error messages - copy and paste them instead.

You need to make sure that the images are in a directory named `anim` that is a subdirectory of the directory where you run the command, that is, the `anim` directory should be under `fbspinner`. It looks like you put the `anim` directory under `scripts`, which is wrong.

**Comment by axonasif** [comment]
> Please don't screenshot error messages - copy and paste them instead.
> 
> You need to make sure that the images are in a directory named `anim` that is a subdirectory of the directory where you run the command, that is, the `anim` directory should be under `fbspinner`. It looks like you put the `anim` directory under `scripts`, which is wrong.

Oh sorry about that, thought it'd be better in this case.
Anyways, now that I've moved `anim` dir a level back from `scripts` dir which means the `fbspinner` dir, I get this error:
```python
$ python3 scripts/flatten.py

Traceback (most recent call last):
  File "scripts/flatten.py", line 31, in <module>
    main()
  File "scripts/flatten.py", line 11, in main
    [flatten(imread(path)) for path in sorted(glob.glob("anim/frame*.png"))]
  File "scripts/flatten.py", line 11, in <listcomp>
    [flatten(imread(path)) for path in sorted(glob.glob("anim/frame*.png"))]
  File "scripts/flatten.py", line 24, in flatten
    assert bpp == 3
AssertionError
```
Here is a log from `tree`:
```fix
$ tree

.
├── anim
│   ├── frame001.png
│   ├── frame002.png
│   ├── frame003.png
│   ├── frame004.png
│   ├── frame005.png
│   ├── frame006.png
│   └── frame007.png
├── butterfly.gif
├── Cargo.lock
├── Cargo.toml
├── PKGBUILD
├── README.md
├── scripts
│   ├── convert.py
│   └── flatten.py
├── share
│   └── anim.bin
├── src
│   ├── bin
│   │   └── fbspinner.rs
│   ├── framebuffer.rs
│   └── lib.rs
└── systemd
    ├── fbspinner-quit.service
    └── fbspinner.service

6 directories, 20 files
```

**Comment by axonasif** [comment]
It appears that if I change `assert bpp == 3` to `assert bpp == 4` on [line 24 of flatten.py](https://github.com/Mortal/fbspinner/blob/596a613a258b86525ae0e23d338531419a924d9b/scripts/flatten.py#L24) then I can successfully get an `anim.bin` but on executing `fbspinner` with that anim.bin I see a scrapped rectangular white image instead.

**Comment by Mortal** [comment]
I'm guessing that your PNG files have an alpha channel, which is why `bpp` is 4 instead of the 3 that the code expects. The assertion should be kept as it is, since it ensures that the output of the function is correct. When you change the assert, you indirectly change the `anim.bin` format, but that would also require changes in the Rust code that reads `anim.bin`.

I would rather add code in `flatten.py` to handle the `bpp>3` case like so:

```
    if im.ndim == 2:
        im = im[:, :, np.newaxis]
        im = im[:, :, [0, 0, 0]]
    elif im.shape[2] > 3:
        im = im[:, :, :3]
```

Would you try it out?

**Comment by axonasif** [comment]
> I'm guessing that your PNG files have an alpha channel, which is why `bpp` is 4 instead of the 3 that the code expects. The assertion should be kept as it is, since it ensures that the output of the function is correct. When you change the assert, you indirectly change the `anim.bin` format, but that would also require changes in the Rust code that reads `anim.bin`.
> 
> I would rather add code in `flatten.py` to handle the `bpp>3` case like so:
> 
> ```
>     if im.ndim == 2:
>         im = im[:, :, np.newaxis]
>         im = im[:, :, [0, 0, 0]]
>     elif im.shape[2] > 3:
>         im = im[:, :, :3]
> ```
> 
> Would you try it out?

Yay, It works!
Btw, should I create a pull request with the following change ?
Thanks for helping me out, really appreciate it ;)

**Comment by Mortal** [comment]
> Btw, should I create a pull request with the following change ?
> Thanks for helping me out, really appreciate it ;)

Yes, please do! Also, if you want to contribute some notes on how to run the scripts, that would be appreciated.

**Comment by axonasif** [comment]
> > Btw, should I create a pull request with the following change ?
> > Thanks for helping me out, really appreciate it ;)
> 
> Yes, please do! Also, if you want to contribute some notes on how to run the scripts, that would be appreciated.

Yes of course, thank you again :)
