### ISSUE TITLE
Frames

### ISSUE THREAD

**Issue by Picoseconds** [Mortal/fbspinner#4]
Can I have Windows bootanim frames? for 1920x1080 monitor

**Comment by Mortal** [comment]
Sorry, don't have the full frames lying around anymore. You can [download Internet Explorer VMs from Microsoft for free](https://www.google.com/search?q=download+internet+explorer+virtual+machine) and screengrab from them - that's how I got the frames in the first place.

**Comment by Picoseconds** [comment]
Alright, thanks!
